//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFormsSoapClient.ClienteService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactoDto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ContactoDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private int ClienteIdField;
        
        private int TipoContactoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClienteNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoContactoDescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int ClienteId {
            get {
                return this.ClienteIdField;
            }
            set {
                if ((this.ClienteIdField.Equals(value) != true)) {
                    this.ClienteIdField = value;
                    this.RaisePropertyChanged("ClienteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int TipoContactoId {
            get {
                return this.TipoContactoIdField;
            }
            set {
                if ((this.TipoContactoIdField.Equals(value) != true)) {
                    this.TipoContactoIdField = value;
                    this.RaisePropertyChanged("TipoContactoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((object.ReferenceEquals(this.ValorField, value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ClienteNombre {
            get {
                return this.ClienteNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteNombreField, value) != true)) {
                    this.ClienteNombreField = value;
                    this.RaisePropertyChanged("ClienteNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string TipoContactoDescripcion {
            get {
                return this.TipoContactoDescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoContactoDescripcionField, value) != true)) {
                    this.TipoContactoDescripcionField = value;
                    this.RaisePropertyChanged("TipoContactoDescripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoContacto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TipoContacto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contacto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Contacto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private int ClienteIdField;
        
        private int TipoContactoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebFormsSoapClient.ClienteService.Cliente ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebFormsSoapClient.ClienteService.TipoContacto TipoContactoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClienteNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoContactoDescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int ClienteId {
            get {
                return this.ClienteIdField;
            }
            set {
                if ((this.ClienteIdField.Equals(value) != true)) {
                    this.ClienteIdField = value;
                    this.RaisePropertyChanged("ClienteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int TipoContactoId {
            get {
                return this.TipoContactoIdField;
            }
            set {
                if ((this.TipoContactoIdField.Equals(value) != true)) {
                    this.TipoContactoIdField = value;
                    this.RaisePropertyChanged("TipoContactoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((object.ReferenceEquals(this.ValorField, value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public WebFormsSoapClient.ClienteService.Cliente Cliente {
            get {
                return this.ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteField, value) != true)) {
                    this.ClienteField = value;
                    this.RaisePropertyChanged("Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public WebFormsSoapClient.ClienteService.TipoContacto TipoContacto {
            get {
                return this.TipoContactoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoContactoField, value) != true)) {
                    this.TipoContactoField = value;
                    this.RaisePropertyChanged("TipoContacto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ClienteNombre {
            get {
                return this.ClienteNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteNombreField, value) != true)) {
                    this.ClienteNombreField = value;
                    this.RaisePropertyChanged("ClienteNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string TipoContactoDescripcion {
            get {
                return this.TipoContactoDescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoContactoDescripcionField, value) != true)) {
                    this.TipoContactoDescripcionField = value;
                    this.RaisePropertyChanged("TipoContactoDescripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClienteService.ClienteServiceSoap")]
    public interface ClienteServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerClienteResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCliente", ReplyAction="*")]
        WebFormsSoapClient.ClienteService.ObtenerClienteResponse ObtenerCliente(WebFormsSoapClient.ClienteService.ObtenerClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<WebFormsSoapClient.ClienteService.ObtenerClienteResponse> ObtenerClienteAsync(WebFormsSoapClient.ClienteService.ObtenerClienteRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerClientesResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerClientes", ReplyAction="*")]
        WebFormsSoapClient.ClienteService.ObtenerClientesResponse ObtenerClientes(WebFormsSoapClient.ClienteService.ObtenerClientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerClientes", ReplyAction="*")]
        System.Threading.Tasks.Task<WebFormsSoapClient.ClienteService.ObtenerClientesResponse> ObtenerClientesAsync(WebFormsSoapClient.ClienteService.ObtenerClientesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cliente del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrearCliente", ReplyAction="*")]
        WebFormsSoapClient.ClienteService.CrearClienteResponse CrearCliente(WebFormsSoapClient.ClienteService.CrearClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrearCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<WebFormsSoapClient.ClienteService.CrearClienteResponse> CrearClienteAsync(WebFormsSoapClient.ClienteService.CrearClienteRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cliente del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarCliente", ReplyAction="*")]
        WebFormsSoapClient.ClienteService.ActualizarClienteResponse ActualizarCliente(WebFormsSoapClient.ClienteService.ActualizarClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<WebFormsSoapClient.ClienteService.ActualizarClienteResponse> ActualizarClienteAsync(WebFormsSoapClient.ClienteService.ActualizarClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarCliente", ReplyAction="*")]
        bool EliminarCliente(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> EliminarClienteAsync(int id);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerContactosResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerContactos", ReplyAction="*")]
        WebFormsSoapClient.ClienteService.ObtenerContactosResponse ObtenerContactos(WebFormsSoapClient.ClienteService.ObtenerContactosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerContactos", ReplyAction="*")]
        System.Threading.Tasks.Task<WebFormsSoapClient.ClienteService.ObtenerContactosResponse> ObtenerContactosAsync(WebFormsSoapClient.ClienteService.ObtenerContactosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerTiposContactoResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerTiposContacto", ReplyAction="*")]
        WebFormsSoapClient.ClienteService.ObtenerTiposContactoResponse ObtenerTiposContacto(WebFormsSoapClient.ClienteService.ObtenerTiposContactoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerTiposContacto", ReplyAction="*")]
        System.Threading.Tasks.Task<WebFormsSoapClient.ClienteService.ObtenerTiposContactoResponse> ObtenerTiposContactoAsync(WebFormsSoapClient.ClienteService.ObtenerTiposContactoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento contacto del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrearContacto", ReplyAction="*")]
        WebFormsSoapClient.ClienteService.CrearContactoResponse CrearContacto(WebFormsSoapClient.ClienteService.CrearContactoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrearContacto", ReplyAction="*")]
        System.Threading.Tasks.Task<WebFormsSoapClient.ClienteService.CrearContactoResponse> CrearContactoAsync(WebFormsSoapClient.ClienteService.CrearContactoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento contacto del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarContacto", ReplyAction="*")]
        WebFormsSoapClient.ClienteService.ActualizarContactoResponse ActualizarContacto(WebFormsSoapClient.ClienteService.ActualizarContactoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarContacto", ReplyAction="*")]
        System.Threading.Tasks.Task<WebFormsSoapClient.ClienteService.ActualizarContactoResponse> ActualizarContactoAsync(WebFormsSoapClient.ClienteService.ActualizarContactoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarContacto", ReplyAction="*")]
        bool EliminarContacto(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarContacto", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> EliminarContactoAsync(int id);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerTipoContactoResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerTipoContacto", ReplyAction="*")]
        WebFormsSoapClient.ClienteService.ObtenerTipoContactoResponse ObtenerTipoContacto(WebFormsSoapClient.ClienteService.ObtenerTipoContactoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerTipoContacto", ReplyAction="*")]
        System.Threading.Tasks.Task<WebFormsSoapClient.ClienteService.ObtenerTipoContactoResponse> ObtenerTipoContactoAsync(WebFormsSoapClient.ClienteService.ObtenerTipoContactoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento tipoContacto del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrearTipoContacto", ReplyAction="*")]
        WebFormsSoapClient.ClienteService.CrearTipoContactoResponse CrearTipoContacto(WebFormsSoapClient.ClienteService.CrearTipoContactoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrearTipoContacto", ReplyAction="*")]
        System.Threading.Tasks.Task<WebFormsSoapClient.ClienteService.CrearTipoContactoResponse> CrearTipoContactoAsync(WebFormsSoapClient.ClienteService.CrearTipoContactoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento tipoContacto del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarTipoContacto", ReplyAction="*")]
        WebFormsSoapClient.ClienteService.ActualizarTipoContactoResponse ActualizarTipoContacto(WebFormsSoapClient.ClienteService.ActualizarTipoContactoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarTipoContacto", ReplyAction="*")]
        System.Threading.Tasks.Task<WebFormsSoapClient.ClienteService.ActualizarTipoContactoResponse> ActualizarTipoContactoAsync(WebFormsSoapClient.ClienteService.ActualizarTipoContactoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarTipoContacto", ReplyAction="*")]
        bool EliminarTipoContacto(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarTipoContacto", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> EliminarTipoContactoAsync(int id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCliente", Namespace="http://tempuri.org/", Order=0)]
        public WebFormsSoapClient.ClienteService.ObtenerClienteRequestBody Body;
        
        public ObtenerClienteRequest() {
        }
        
        public ObtenerClienteRequest(WebFormsSoapClient.ClienteService.ObtenerClienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerClienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public ObtenerClienteRequestBody() {
        }
        
        public ObtenerClienteRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerClienteResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebFormsSoapClient.ClienteService.ObtenerClienteResponseBody Body;
        
        public ObtenerClienteResponse() {
        }
        
        public ObtenerClienteResponse(WebFormsSoapClient.ClienteService.ObtenerClienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerClienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebFormsSoapClient.ClienteService.Cliente ObtenerClienteResult;
        
        public ObtenerClienteResponseBody() {
        }
        
        public ObtenerClienteResponseBody(WebFormsSoapClient.ClienteService.Cliente ObtenerClienteResult) {
            this.ObtenerClienteResult = ObtenerClienteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerClientesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerClientes", Namespace="http://tempuri.org/", Order=0)]
        public WebFormsSoapClient.ClienteService.ObtenerClientesRequestBody Body;
        
        public ObtenerClientesRequest() {
        }
        
        public ObtenerClientesRequest(WebFormsSoapClient.ClienteService.ObtenerClientesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObtenerClientesRequestBody {
        
        public ObtenerClientesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerClientesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerClientesResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebFormsSoapClient.ClienteService.ObtenerClientesResponseBody Body;
        
        public ObtenerClientesResponse() {
        }
        
        public ObtenerClientesResponse(WebFormsSoapClient.ClienteService.ObtenerClientesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerClientesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebFormsSoapClient.ClienteService.Cliente[] ObtenerClientesResult;
        
        public ObtenerClientesResponseBody() {
        }
        
        public ObtenerClientesResponseBody(WebFormsSoapClient.ClienteService.Cliente[] ObtenerClientesResult) {
            this.ObtenerClientesResult = ObtenerClientesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CrearClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CrearCliente", Namespace="http://tempuri.org/", Order=0)]
        public WebFormsSoapClient.ClienteService.CrearClienteRequestBody Body;
        
        public CrearClienteRequest() {
        }
        
        public CrearClienteRequest(WebFormsSoapClient.ClienteService.CrearClienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CrearClienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebFormsSoapClient.ClienteService.Cliente cliente;
        
        public CrearClienteRequestBody() {
        }
        
        public CrearClienteRequestBody(WebFormsSoapClient.ClienteService.Cliente cliente) {
            this.cliente = cliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CrearClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CrearClienteResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebFormsSoapClient.ClienteService.CrearClienteResponseBody Body;
        
        public CrearClienteResponse() {
        }
        
        public CrearClienteResponse(WebFormsSoapClient.ClienteService.CrearClienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CrearClienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CrearClienteResult;
        
        public CrearClienteResponseBody() {
        }
        
        public CrearClienteResponseBody(int CrearClienteResult) {
            this.CrearClienteResult = CrearClienteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarCliente", Namespace="http://tempuri.org/", Order=0)]
        public WebFormsSoapClient.ClienteService.ActualizarClienteRequestBody Body;
        
        public ActualizarClienteRequest() {
        }
        
        public ActualizarClienteRequest(WebFormsSoapClient.ClienteService.ActualizarClienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarClienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebFormsSoapClient.ClienteService.Cliente cliente;
        
        public ActualizarClienteRequestBody() {
        }
        
        public ActualizarClienteRequestBody(WebFormsSoapClient.ClienteService.Cliente cliente) {
            this.cliente = cliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarClienteResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebFormsSoapClient.ClienteService.ActualizarClienteResponseBody Body;
        
        public ActualizarClienteResponse() {
        }
        
        public ActualizarClienteResponse(WebFormsSoapClient.ClienteService.ActualizarClienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarClienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ActualizarClienteResult;
        
        public ActualizarClienteResponseBody() {
        }
        
        public ActualizarClienteResponseBody(bool ActualizarClienteResult) {
            this.ActualizarClienteResult = ActualizarClienteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerContactosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerContactos", Namespace="http://tempuri.org/", Order=0)]
        public WebFormsSoapClient.ClienteService.ObtenerContactosRequestBody Body;
        
        public ObtenerContactosRequest() {
        }
        
        public ObtenerContactosRequest(WebFormsSoapClient.ClienteService.ObtenerContactosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObtenerContactosRequestBody {
        
        public ObtenerContactosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerContactosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerContactosResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebFormsSoapClient.ClienteService.ObtenerContactosResponseBody Body;
        
        public ObtenerContactosResponse() {
        }
        
        public ObtenerContactosResponse(WebFormsSoapClient.ClienteService.ObtenerContactosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerContactosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebFormsSoapClient.ClienteService.ContactoDto[] ObtenerContactosResult;
        
        public ObtenerContactosResponseBody() {
        }
        
        public ObtenerContactosResponseBody(WebFormsSoapClient.ClienteService.ContactoDto[] ObtenerContactosResult) {
            this.ObtenerContactosResult = ObtenerContactosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerTiposContactoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerTiposContacto", Namespace="http://tempuri.org/", Order=0)]
        public WebFormsSoapClient.ClienteService.ObtenerTiposContactoRequestBody Body;
        
        public ObtenerTiposContactoRequest() {
        }
        
        public ObtenerTiposContactoRequest(WebFormsSoapClient.ClienteService.ObtenerTiposContactoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObtenerTiposContactoRequestBody {
        
        public ObtenerTiposContactoRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerTiposContactoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerTiposContactoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebFormsSoapClient.ClienteService.ObtenerTiposContactoResponseBody Body;
        
        public ObtenerTiposContactoResponse() {
        }
        
        public ObtenerTiposContactoResponse(WebFormsSoapClient.ClienteService.ObtenerTiposContactoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerTiposContactoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebFormsSoapClient.ClienteService.TipoContacto[] ObtenerTiposContactoResult;
        
        public ObtenerTiposContactoResponseBody() {
        }
        
        public ObtenerTiposContactoResponseBody(WebFormsSoapClient.ClienteService.TipoContacto[] ObtenerTiposContactoResult) {
            this.ObtenerTiposContactoResult = ObtenerTiposContactoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CrearContactoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CrearContacto", Namespace="http://tempuri.org/", Order=0)]
        public WebFormsSoapClient.ClienteService.CrearContactoRequestBody Body;
        
        public CrearContactoRequest() {
        }
        
        public CrearContactoRequest(WebFormsSoapClient.ClienteService.CrearContactoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CrearContactoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebFormsSoapClient.ClienteService.Contacto contacto;
        
        public CrearContactoRequestBody() {
        }
        
        public CrearContactoRequestBody(WebFormsSoapClient.ClienteService.Contacto contacto) {
            this.contacto = contacto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CrearContactoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CrearContactoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebFormsSoapClient.ClienteService.CrearContactoResponseBody Body;
        
        public CrearContactoResponse() {
        }
        
        public CrearContactoResponse(WebFormsSoapClient.ClienteService.CrearContactoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CrearContactoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CrearContactoResult;
        
        public CrearContactoResponseBody() {
        }
        
        public CrearContactoResponseBody(int CrearContactoResult) {
            this.CrearContactoResult = CrearContactoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarContactoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarContacto", Namespace="http://tempuri.org/", Order=0)]
        public WebFormsSoapClient.ClienteService.ActualizarContactoRequestBody Body;
        
        public ActualizarContactoRequest() {
        }
        
        public ActualizarContactoRequest(WebFormsSoapClient.ClienteService.ActualizarContactoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarContactoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebFormsSoapClient.ClienteService.Contacto contacto;
        
        public ActualizarContactoRequestBody() {
        }
        
        public ActualizarContactoRequestBody(WebFormsSoapClient.ClienteService.Contacto contacto) {
            this.contacto = contacto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarContactoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarContactoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebFormsSoapClient.ClienteService.ActualizarContactoResponseBody Body;
        
        public ActualizarContactoResponse() {
        }
        
        public ActualizarContactoResponse(WebFormsSoapClient.ClienteService.ActualizarContactoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarContactoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ActualizarContactoResult;
        
        public ActualizarContactoResponseBody() {
        }
        
        public ActualizarContactoResponseBody(bool ActualizarContactoResult) {
            this.ActualizarContactoResult = ActualizarContactoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerTipoContactoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerTipoContacto", Namespace="http://tempuri.org/", Order=0)]
        public WebFormsSoapClient.ClienteService.ObtenerTipoContactoRequestBody Body;
        
        public ObtenerTipoContactoRequest() {
        }
        
        public ObtenerTipoContactoRequest(WebFormsSoapClient.ClienteService.ObtenerTipoContactoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerTipoContactoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public ObtenerTipoContactoRequestBody() {
        }
        
        public ObtenerTipoContactoRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerTipoContactoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerTipoContactoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebFormsSoapClient.ClienteService.ObtenerTipoContactoResponseBody Body;
        
        public ObtenerTipoContactoResponse() {
        }
        
        public ObtenerTipoContactoResponse(WebFormsSoapClient.ClienteService.ObtenerTipoContactoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerTipoContactoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebFormsSoapClient.ClienteService.TipoContacto ObtenerTipoContactoResult;
        
        public ObtenerTipoContactoResponseBody() {
        }
        
        public ObtenerTipoContactoResponseBody(WebFormsSoapClient.ClienteService.TipoContacto ObtenerTipoContactoResult) {
            this.ObtenerTipoContactoResult = ObtenerTipoContactoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CrearTipoContactoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CrearTipoContacto", Namespace="http://tempuri.org/", Order=0)]
        public WebFormsSoapClient.ClienteService.CrearTipoContactoRequestBody Body;
        
        public CrearTipoContactoRequest() {
        }
        
        public CrearTipoContactoRequest(WebFormsSoapClient.ClienteService.CrearTipoContactoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CrearTipoContactoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebFormsSoapClient.ClienteService.TipoContacto tipoContacto;
        
        public CrearTipoContactoRequestBody() {
        }
        
        public CrearTipoContactoRequestBody(WebFormsSoapClient.ClienteService.TipoContacto tipoContacto) {
            this.tipoContacto = tipoContacto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CrearTipoContactoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CrearTipoContactoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebFormsSoapClient.ClienteService.CrearTipoContactoResponseBody Body;
        
        public CrearTipoContactoResponse() {
        }
        
        public CrearTipoContactoResponse(WebFormsSoapClient.ClienteService.CrearTipoContactoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CrearTipoContactoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CrearTipoContactoResult;
        
        public CrearTipoContactoResponseBody() {
        }
        
        public CrearTipoContactoResponseBody(int CrearTipoContactoResult) {
            this.CrearTipoContactoResult = CrearTipoContactoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarTipoContactoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarTipoContacto", Namespace="http://tempuri.org/", Order=0)]
        public WebFormsSoapClient.ClienteService.ActualizarTipoContactoRequestBody Body;
        
        public ActualizarTipoContactoRequest() {
        }
        
        public ActualizarTipoContactoRequest(WebFormsSoapClient.ClienteService.ActualizarTipoContactoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarTipoContactoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebFormsSoapClient.ClienteService.TipoContacto tipoContacto;
        
        public ActualizarTipoContactoRequestBody() {
        }
        
        public ActualizarTipoContactoRequestBody(WebFormsSoapClient.ClienteService.TipoContacto tipoContacto) {
            this.tipoContacto = tipoContacto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarTipoContactoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarTipoContactoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebFormsSoapClient.ClienteService.ActualizarTipoContactoResponseBody Body;
        
        public ActualizarTipoContactoResponse() {
        }
        
        public ActualizarTipoContactoResponse(WebFormsSoapClient.ClienteService.ActualizarTipoContactoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarTipoContactoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ActualizarTipoContactoResult;
        
        public ActualizarTipoContactoResponseBody() {
        }
        
        public ActualizarTipoContactoResponseBody(bool ActualizarTipoContactoResult) {
            this.ActualizarTipoContactoResult = ActualizarTipoContactoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ClienteServiceSoapChannel : WebFormsSoapClient.ClienteService.ClienteServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClienteServiceSoapClient : System.ServiceModel.ClientBase<WebFormsSoapClient.ClienteService.ClienteServiceSoap>, WebFormsSoapClient.ClienteService.ClienteServiceSoap {
        
        public ClienteServiceSoapClient() {
        }
        
        public ClienteServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClienteServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebFormsSoapClient.ClienteService.ObtenerClienteResponse WebFormsSoapClient.ClienteService.ClienteServiceSoap.ObtenerCliente(WebFormsSoapClient.ClienteService.ObtenerClienteRequest request) {
            return base.Channel.ObtenerCliente(request);
        }
        
        public WebFormsSoapClient.ClienteService.Cliente ObtenerCliente(int id) {
            WebFormsSoapClient.ClienteService.ObtenerClienteRequest inValue = new WebFormsSoapClient.ClienteService.ObtenerClienteRequest();
            inValue.Body = new WebFormsSoapClient.ClienteService.ObtenerClienteRequestBody();
            inValue.Body.id = id;
            WebFormsSoapClient.ClienteService.ObtenerClienteResponse retVal = ((WebFormsSoapClient.ClienteService.ClienteServiceSoap)(this)).ObtenerCliente(inValue);
            return retVal.Body.ObtenerClienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebFormsSoapClient.ClienteService.ObtenerClienteResponse> WebFormsSoapClient.ClienteService.ClienteServiceSoap.ObtenerClienteAsync(WebFormsSoapClient.ClienteService.ObtenerClienteRequest request) {
            return base.Channel.ObtenerClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebFormsSoapClient.ClienteService.ObtenerClienteResponse> ObtenerClienteAsync(int id) {
            WebFormsSoapClient.ClienteService.ObtenerClienteRequest inValue = new WebFormsSoapClient.ClienteService.ObtenerClienteRequest();
            inValue.Body = new WebFormsSoapClient.ClienteService.ObtenerClienteRequestBody();
            inValue.Body.id = id;
            return ((WebFormsSoapClient.ClienteService.ClienteServiceSoap)(this)).ObtenerClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebFormsSoapClient.ClienteService.ObtenerClientesResponse WebFormsSoapClient.ClienteService.ClienteServiceSoap.ObtenerClientes(WebFormsSoapClient.ClienteService.ObtenerClientesRequest request) {
            return base.Channel.ObtenerClientes(request);
        }
        
        public WebFormsSoapClient.ClienteService.Cliente[] ObtenerClientes() {
            WebFormsSoapClient.ClienteService.ObtenerClientesRequest inValue = new WebFormsSoapClient.ClienteService.ObtenerClientesRequest();
            inValue.Body = new WebFormsSoapClient.ClienteService.ObtenerClientesRequestBody();
            WebFormsSoapClient.ClienteService.ObtenerClientesResponse retVal = ((WebFormsSoapClient.ClienteService.ClienteServiceSoap)(this)).ObtenerClientes(inValue);
            return retVal.Body.ObtenerClientesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebFormsSoapClient.ClienteService.ObtenerClientesResponse> WebFormsSoapClient.ClienteService.ClienteServiceSoap.ObtenerClientesAsync(WebFormsSoapClient.ClienteService.ObtenerClientesRequest request) {
            return base.Channel.ObtenerClientesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebFormsSoapClient.ClienteService.ObtenerClientesResponse> ObtenerClientesAsync() {
            WebFormsSoapClient.ClienteService.ObtenerClientesRequest inValue = new WebFormsSoapClient.ClienteService.ObtenerClientesRequest();
            inValue.Body = new WebFormsSoapClient.ClienteService.ObtenerClientesRequestBody();
            return ((WebFormsSoapClient.ClienteService.ClienteServiceSoap)(this)).ObtenerClientesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebFormsSoapClient.ClienteService.CrearClienteResponse WebFormsSoapClient.ClienteService.ClienteServiceSoap.CrearCliente(WebFormsSoapClient.ClienteService.CrearClienteRequest request) {
            return base.Channel.CrearCliente(request);
        }
        
        public int CrearCliente(WebFormsSoapClient.ClienteService.Cliente cliente) {
            WebFormsSoapClient.ClienteService.CrearClienteRequest inValue = new WebFormsSoapClient.ClienteService.CrearClienteRequest();
            inValue.Body = new WebFormsSoapClient.ClienteService.CrearClienteRequestBody();
            inValue.Body.cliente = cliente;
            WebFormsSoapClient.ClienteService.CrearClienteResponse retVal = ((WebFormsSoapClient.ClienteService.ClienteServiceSoap)(this)).CrearCliente(inValue);
            return retVal.Body.CrearClienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebFormsSoapClient.ClienteService.CrearClienteResponse> WebFormsSoapClient.ClienteService.ClienteServiceSoap.CrearClienteAsync(WebFormsSoapClient.ClienteService.CrearClienteRequest request) {
            return base.Channel.CrearClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebFormsSoapClient.ClienteService.CrearClienteResponse> CrearClienteAsync(WebFormsSoapClient.ClienteService.Cliente cliente) {
            WebFormsSoapClient.ClienteService.CrearClienteRequest inValue = new WebFormsSoapClient.ClienteService.CrearClienteRequest();
            inValue.Body = new WebFormsSoapClient.ClienteService.CrearClienteRequestBody();
            inValue.Body.cliente = cliente;
            return ((WebFormsSoapClient.ClienteService.ClienteServiceSoap)(this)).CrearClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebFormsSoapClient.ClienteService.ActualizarClienteResponse WebFormsSoapClient.ClienteService.ClienteServiceSoap.ActualizarCliente(WebFormsSoapClient.ClienteService.ActualizarClienteRequest request) {
            return base.Channel.ActualizarCliente(request);
        }
        
        public bool ActualizarCliente(WebFormsSoapClient.ClienteService.Cliente cliente) {
            WebFormsSoapClient.ClienteService.ActualizarClienteRequest inValue = new WebFormsSoapClient.ClienteService.ActualizarClienteRequest();
            inValue.Body = new WebFormsSoapClient.ClienteService.ActualizarClienteRequestBody();
            inValue.Body.cliente = cliente;
            WebFormsSoapClient.ClienteService.ActualizarClienteResponse retVal = ((WebFormsSoapClient.ClienteService.ClienteServiceSoap)(this)).ActualizarCliente(inValue);
            return retVal.Body.ActualizarClienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebFormsSoapClient.ClienteService.ActualizarClienteResponse> WebFormsSoapClient.ClienteService.ClienteServiceSoap.ActualizarClienteAsync(WebFormsSoapClient.ClienteService.ActualizarClienteRequest request) {
            return base.Channel.ActualizarClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebFormsSoapClient.ClienteService.ActualizarClienteResponse> ActualizarClienteAsync(WebFormsSoapClient.ClienteService.Cliente cliente) {
            WebFormsSoapClient.ClienteService.ActualizarClienteRequest inValue = new WebFormsSoapClient.ClienteService.ActualizarClienteRequest();
            inValue.Body = new WebFormsSoapClient.ClienteService.ActualizarClienteRequestBody();
            inValue.Body.cliente = cliente;
            return ((WebFormsSoapClient.ClienteService.ClienteServiceSoap)(this)).ActualizarClienteAsync(inValue);
        }
        
        public bool EliminarCliente(int id) {
            return base.Channel.EliminarCliente(id);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarClienteAsync(int id) {
            return base.Channel.EliminarClienteAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebFormsSoapClient.ClienteService.ObtenerContactosResponse WebFormsSoapClient.ClienteService.ClienteServiceSoap.ObtenerContactos(WebFormsSoapClient.ClienteService.ObtenerContactosRequest request) {
            return base.Channel.ObtenerContactos(request);
        }
        
        public WebFormsSoapClient.ClienteService.ContactoDto[] ObtenerContactos() {
            WebFormsSoapClient.ClienteService.ObtenerContactosRequest inValue = new WebFormsSoapClient.ClienteService.ObtenerContactosRequest();
            inValue.Body = new WebFormsSoapClient.ClienteService.ObtenerContactosRequestBody();
            WebFormsSoapClient.ClienteService.ObtenerContactosResponse retVal = ((WebFormsSoapClient.ClienteService.ClienteServiceSoap)(this)).ObtenerContactos(inValue);
            return retVal.Body.ObtenerContactosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebFormsSoapClient.ClienteService.ObtenerContactosResponse> WebFormsSoapClient.ClienteService.ClienteServiceSoap.ObtenerContactosAsync(WebFormsSoapClient.ClienteService.ObtenerContactosRequest request) {
            return base.Channel.ObtenerContactosAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebFormsSoapClient.ClienteService.ObtenerContactosResponse> ObtenerContactosAsync() {
            WebFormsSoapClient.ClienteService.ObtenerContactosRequest inValue = new WebFormsSoapClient.ClienteService.ObtenerContactosRequest();
            inValue.Body = new WebFormsSoapClient.ClienteService.ObtenerContactosRequestBody();
            return ((WebFormsSoapClient.ClienteService.ClienteServiceSoap)(this)).ObtenerContactosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebFormsSoapClient.ClienteService.ObtenerTiposContactoResponse WebFormsSoapClient.ClienteService.ClienteServiceSoap.ObtenerTiposContacto(WebFormsSoapClient.ClienteService.ObtenerTiposContactoRequest request) {
            return base.Channel.ObtenerTiposContacto(request);
        }
        
        public WebFormsSoapClient.ClienteService.TipoContacto[] ObtenerTiposContacto() {
            WebFormsSoapClient.ClienteService.ObtenerTiposContactoRequest inValue = new WebFormsSoapClient.ClienteService.ObtenerTiposContactoRequest();
            inValue.Body = new WebFormsSoapClient.ClienteService.ObtenerTiposContactoRequestBody();
            WebFormsSoapClient.ClienteService.ObtenerTiposContactoResponse retVal = ((WebFormsSoapClient.ClienteService.ClienteServiceSoap)(this)).ObtenerTiposContacto(inValue);
            return retVal.Body.ObtenerTiposContactoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebFormsSoapClient.ClienteService.ObtenerTiposContactoResponse> WebFormsSoapClient.ClienteService.ClienteServiceSoap.ObtenerTiposContactoAsync(WebFormsSoapClient.ClienteService.ObtenerTiposContactoRequest request) {
            return base.Channel.ObtenerTiposContactoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebFormsSoapClient.ClienteService.ObtenerTiposContactoResponse> ObtenerTiposContactoAsync() {
            WebFormsSoapClient.ClienteService.ObtenerTiposContactoRequest inValue = new WebFormsSoapClient.ClienteService.ObtenerTiposContactoRequest();
            inValue.Body = new WebFormsSoapClient.ClienteService.ObtenerTiposContactoRequestBody();
            return ((WebFormsSoapClient.ClienteService.ClienteServiceSoap)(this)).ObtenerTiposContactoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebFormsSoapClient.ClienteService.CrearContactoResponse WebFormsSoapClient.ClienteService.ClienteServiceSoap.CrearContacto(WebFormsSoapClient.ClienteService.CrearContactoRequest request) {
            return base.Channel.CrearContacto(request);
        }
        
        public int CrearContacto(WebFormsSoapClient.ClienteService.Contacto contacto) {
            WebFormsSoapClient.ClienteService.CrearContactoRequest inValue = new WebFormsSoapClient.ClienteService.CrearContactoRequest();
            inValue.Body = new WebFormsSoapClient.ClienteService.CrearContactoRequestBody();
            inValue.Body.contacto = contacto;
            WebFormsSoapClient.ClienteService.CrearContactoResponse retVal = ((WebFormsSoapClient.ClienteService.ClienteServiceSoap)(this)).CrearContacto(inValue);
            return retVal.Body.CrearContactoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebFormsSoapClient.ClienteService.CrearContactoResponse> WebFormsSoapClient.ClienteService.ClienteServiceSoap.CrearContactoAsync(WebFormsSoapClient.ClienteService.CrearContactoRequest request) {
            return base.Channel.CrearContactoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebFormsSoapClient.ClienteService.CrearContactoResponse> CrearContactoAsync(WebFormsSoapClient.ClienteService.Contacto contacto) {
            WebFormsSoapClient.ClienteService.CrearContactoRequest inValue = new WebFormsSoapClient.ClienteService.CrearContactoRequest();
            inValue.Body = new WebFormsSoapClient.ClienteService.CrearContactoRequestBody();
            inValue.Body.contacto = contacto;
            return ((WebFormsSoapClient.ClienteService.ClienteServiceSoap)(this)).CrearContactoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebFormsSoapClient.ClienteService.ActualizarContactoResponse WebFormsSoapClient.ClienteService.ClienteServiceSoap.ActualizarContacto(WebFormsSoapClient.ClienteService.ActualizarContactoRequest request) {
            return base.Channel.ActualizarContacto(request);
        }
        
        public bool ActualizarContacto(WebFormsSoapClient.ClienteService.Contacto contacto) {
            WebFormsSoapClient.ClienteService.ActualizarContactoRequest inValue = new WebFormsSoapClient.ClienteService.ActualizarContactoRequest();
            inValue.Body = new WebFormsSoapClient.ClienteService.ActualizarContactoRequestBody();
            inValue.Body.contacto = contacto;
            WebFormsSoapClient.ClienteService.ActualizarContactoResponse retVal = ((WebFormsSoapClient.ClienteService.ClienteServiceSoap)(this)).ActualizarContacto(inValue);
            return retVal.Body.ActualizarContactoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebFormsSoapClient.ClienteService.ActualizarContactoResponse> WebFormsSoapClient.ClienteService.ClienteServiceSoap.ActualizarContactoAsync(WebFormsSoapClient.ClienteService.ActualizarContactoRequest request) {
            return base.Channel.ActualizarContactoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebFormsSoapClient.ClienteService.ActualizarContactoResponse> ActualizarContactoAsync(WebFormsSoapClient.ClienteService.Contacto contacto) {
            WebFormsSoapClient.ClienteService.ActualizarContactoRequest inValue = new WebFormsSoapClient.ClienteService.ActualizarContactoRequest();
            inValue.Body = new WebFormsSoapClient.ClienteService.ActualizarContactoRequestBody();
            inValue.Body.contacto = contacto;
            return ((WebFormsSoapClient.ClienteService.ClienteServiceSoap)(this)).ActualizarContactoAsync(inValue);
        }
        
        public bool EliminarContacto(int id) {
            return base.Channel.EliminarContacto(id);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarContactoAsync(int id) {
            return base.Channel.EliminarContactoAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebFormsSoapClient.ClienteService.ObtenerTipoContactoResponse WebFormsSoapClient.ClienteService.ClienteServiceSoap.ObtenerTipoContacto(WebFormsSoapClient.ClienteService.ObtenerTipoContactoRequest request) {
            return base.Channel.ObtenerTipoContacto(request);
        }
        
        public WebFormsSoapClient.ClienteService.TipoContacto ObtenerTipoContacto(int id) {
            WebFormsSoapClient.ClienteService.ObtenerTipoContactoRequest inValue = new WebFormsSoapClient.ClienteService.ObtenerTipoContactoRequest();
            inValue.Body = new WebFormsSoapClient.ClienteService.ObtenerTipoContactoRequestBody();
            inValue.Body.id = id;
            WebFormsSoapClient.ClienteService.ObtenerTipoContactoResponse retVal = ((WebFormsSoapClient.ClienteService.ClienteServiceSoap)(this)).ObtenerTipoContacto(inValue);
            return retVal.Body.ObtenerTipoContactoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebFormsSoapClient.ClienteService.ObtenerTipoContactoResponse> WebFormsSoapClient.ClienteService.ClienteServiceSoap.ObtenerTipoContactoAsync(WebFormsSoapClient.ClienteService.ObtenerTipoContactoRequest request) {
            return base.Channel.ObtenerTipoContactoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebFormsSoapClient.ClienteService.ObtenerTipoContactoResponse> ObtenerTipoContactoAsync(int id) {
            WebFormsSoapClient.ClienteService.ObtenerTipoContactoRequest inValue = new WebFormsSoapClient.ClienteService.ObtenerTipoContactoRequest();
            inValue.Body = new WebFormsSoapClient.ClienteService.ObtenerTipoContactoRequestBody();
            inValue.Body.id = id;
            return ((WebFormsSoapClient.ClienteService.ClienteServiceSoap)(this)).ObtenerTipoContactoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebFormsSoapClient.ClienteService.CrearTipoContactoResponse WebFormsSoapClient.ClienteService.ClienteServiceSoap.CrearTipoContacto(WebFormsSoapClient.ClienteService.CrearTipoContactoRequest request) {
            return base.Channel.CrearTipoContacto(request);
        }
        
        public int CrearTipoContacto(WebFormsSoapClient.ClienteService.TipoContacto tipoContacto) {
            WebFormsSoapClient.ClienteService.CrearTipoContactoRequest inValue = new WebFormsSoapClient.ClienteService.CrearTipoContactoRequest();
            inValue.Body = new WebFormsSoapClient.ClienteService.CrearTipoContactoRequestBody();
            inValue.Body.tipoContacto = tipoContacto;
            WebFormsSoapClient.ClienteService.CrearTipoContactoResponse retVal = ((WebFormsSoapClient.ClienteService.ClienteServiceSoap)(this)).CrearTipoContacto(inValue);
            return retVal.Body.CrearTipoContactoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebFormsSoapClient.ClienteService.CrearTipoContactoResponse> WebFormsSoapClient.ClienteService.ClienteServiceSoap.CrearTipoContactoAsync(WebFormsSoapClient.ClienteService.CrearTipoContactoRequest request) {
            return base.Channel.CrearTipoContactoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebFormsSoapClient.ClienteService.CrearTipoContactoResponse> CrearTipoContactoAsync(WebFormsSoapClient.ClienteService.TipoContacto tipoContacto) {
            WebFormsSoapClient.ClienteService.CrearTipoContactoRequest inValue = new WebFormsSoapClient.ClienteService.CrearTipoContactoRequest();
            inValue.Body = new WebFormsSoapClient.ClienteService.CrearTipoContactoRequestBody();
            inValue.Body.tipoContacto = tipoContacto;
            return ((WebFormsSoapClient.ClienteService.ClienteServiceSoap)(this)).CrearTipoContactoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebFormsSoapClient.ClienteService.ActualizarTipoContactoResponse WebFormsSoapClient.ClienteService.ClienteServiceSoap.ActualizarTipoContacto(WebFormsSoapClient.ClienteService.ActualizarTipoContactoRequest request) {
            return base.Channel.ActualizarTipoContacto(request);
        }
        
        public bool ActualizarTipoContacto(WebFormsSoapClient.ClienteService.TipoContacto tipoContacto) {
            WebFormsSoapClient.ClienteService.ActualizarTipoContactoRequest inValue = new WebFormsSoapClient.ClienteService.ActualizarTipoContactoRequest();
            inValue.Body = new WebFormsSoapClient.ClienteService.ActualizarTipoContactoRequestBody();
            inValue.Body.tipoContacto = tipoContacto;
            WebFormsSoapClient.ClienteService.ActualizarTipoContactoResponse retVal = ((WebFormsSoapClient.ClienteService.ClienteServiceSoap)(this)).ActualizarTipoContacto(inValue);
            return retVal.Body.ActualizarTipoContactoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebFormsSoapClient.ClienteService.ActualizarTipoContactoResponse> WebFormsSoapClient.ClienteService.ClienteServiceSoap.ActualizarTipoContactoAsync(WebFormsSoapClient.ClienteService.ActualizarTipoContactoRequest request) {
            return base.Channel.ActualizarTipoContactoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebFormsSoapClient.ClienteService.ActualizarTipoContactoResponse> ActualizarTipoContactoAsync(WebFormsSoapClient.ClienteService.TipoContacto tipoContacto) {
            WebFormsSoapClient.ClienteService.ActualizarTipoContactoRequest inValue = new WebFormsSoapClient.ClienteService.ActualizarTipoContactoRequest();
            inValue.Body = new WebFormsSoapClient.ClienteService.ActualizarTipoContactoRequestBody();
            inValue.Body.tipoContacto = tipoContacto;
            return ((WebFormsSoapClient.ClienteService.ClienteServiceSoap)(this)).ActualizarTipoContactoAsync(inValue);
        }
        
        public bool EliminarTipoContacto(int id) {
            return base.Channel.EliminarTipoContacto(id);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarTipoContactoAsync(int id) {
            return base.Channel.EliminarTipoContactoAsync(id);
        }
    }
}
